### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by kbastamow**

### CODE REVIEW

**Comment by kbastamow** [comment]
25/07/2023 - Stripe Api functions:

To resolve/discuss:

- [ ]  **Interfaces - any:** The interfaces for Stripe contain a lot of _any_ values, that are the direct result of the example response on the API page, which contains many _null_ values. When converting from JSON to TypeScript, these become of type "any."
Some of them can be guessed and changed ("nickname" – probably a string!), but for others, I'm not sure about the exact data type. Best approach here?

- [ ] **"Tricky" query parameter types:**  Let's review some of the query parameters types. For example, most dates are described like this: "The value can be a string with an integer Unix timestamp, or it can be a dictionary with the following options: ..." I have used "string | number" as the type, but it needs to be reviewed.
There may be several other parameters where the user has to either refer to the documentation or already know how to use Stripe to correctly set search filters.

- [ ] **Snake case:** The snake case in the code comes directly from the way the target apis format their properties. Should we change this in our code?

**Comment by miguelrk** [comment]
**Interfaces - any**: let's leave types exactly as the translation-tool outputs them (potentially with many `any`s). We can eventually go back and enhance these types very easily. But I would rather move fast now (80-20 principle) and not play the guessing game at all, especially since having a typed interface already takes us to 80% of the benefit, typing the specific fields in the interface is the 20% benefit remaining.... we'll eventually get to it...

**"Tricky" query parameter types**: let's not have multiple types for a single parameter. In the case of a complicated `date` parameter for example (integer Unix timestamp or a dictionary), let's settle on a SINGLE type (the simplest/most flexible). So instead of `string | number`, let's force the user to only use `string` (removing the need to have to handle complex branching logic on our side). And analogously, the same goes for other "tricky" fields. Again, we we'll eventually get to adding better types (80-20 for now)

**Snake case**: yes, since all APIs use different conventions, but here we are developing our own API (our own functions). Therefore it is best for end users (developers) to have all API functions using the same convention: **camelCase**. What each function should then do, is map these function arguments in **camelCase** to their counterparts in the original APIs (be it **snake_case**, **SCREAM_CASE**, or whatever)

**Comment by miguelrk** [comment]
**One more thing:**

Let's also add an exported interface `<API>Options` to the top of each `mod.ts` for each API and to also type the function arguments e.g. `const googlesheets = ({...}: GooglesheetsOptions) => {...}` like bellow:

Screenshot 2023-07-25 5 38 21 PM

**Comment by kbastamow** [comment]
27/07/2023

- Github
- Stripe
- Pipedrive
- Airtable 

These apis have been reviewed according to the following checklist:

- [x] Types for **parameters** and **return values**
- [x] **All query parameters** from original API
- [x] **Custom type unions** where options are limited and known -e.g "public" | "private" 
- [x] **One type** even if original API allows different formats
- [x] **Required / optional** parameters indicated
- [x] **Defaults** provided where appropriate

**Comment by kbastamow** [comment]
27/07/2023 - Shopify api functions

To resolve/discuss: 

- [ ]  **.json** – the api url has a .json ending, e.g. _/admin/api/2023-07/orders.json?status=any_
   From what I understand, this is simply informative and I don’t need to add it to my route.
   **Could you confirm?**

- [ ] **Scope** – different endpoints specify different access requirements like _“Requires ANY of the following access scopes: shopify_payments_payouts, shopify_payments”_. 
**Do we need to worry about these, or are they permissions that are internally defined in the user’s api key?**

- [ ] **Response "Orders"** -  responses from _get orders_ and from _get customer’s orders_ are largely the same, but each has around a dozen properties that the other one doesn’t. Some of these unique properties are in nested objects, which makes it complicated to use pick/omit/extends options, especially since the whole interface is over 600 lines. 
**What might be the best approach here?**

- [ ] **Response length** – Some of the responses are extremely long. They’ve been left as is in interfaces because it’s hard to know what the end user might want.

- [ ] **Add or update customer** – Optional body params. Strangely enough, all data are optional when creating or updating a customer. Doesn’t seem to make sense, but I’ve left it as specified in the original documentation.


- [ ] **Keeping linter happy:** 

1. **Query params** – some functions only allow for one query parameter (typically fields, which is a string). I’ve simplified the query to add this directly to the function rather than creating interface. Now, the linter doesn’t let you add both type and default when the type is simple (e.g. (fields: string = “”) is not allowed), so I’ve left the type out and just added default:

```
async (
    customerId: string,
    fields = "",
  )
```

2) **Mixing of types and interfaces**.  Mostly I've used interfaces, but there are some types because linter complains about an empty interface (not adding any new properties), for example if I try to use interface in the following case:
`export type ProductSpecific = Pick<Product, "id" | "title" | "images">;`

**Comment by miguelrk** [comment]
**.json:**  despite `.json` ending being confusing, using dots in a URL path is perfectly valid. That means `.json` should be included, since `/admin/api/2023-07/orders.json` is not the same path as `/admin/api/2023-07/orders`. Don't know if the API allows omitting it, but let's add it ourselves for our functions e.g. `api['orders.json'].get()`. **NOTE**: the `options.baseURL` of the `api` client for shopify alredy sets `/admin/api/${apiVersion}` on instantiation, so you can access resources directly.

 **Scope:**  No, there's no need to worry about scopes/authentication in the functions. The `api` client should be given the desired permissions upon instantiation, and based on this, usage of functions will throw errors or not (these errors will prompt user to provide necessary permissions, no need to handle this within the functions, it's best to let the API errors "bubble up" for the user to handle himself when using the `api` client).
  
 **Response "Orders":**  tricky one... my first thought was to stop typing the nested levels at some point and use `any` instead (e.g. to reduce from ~600 properties to maybe 50-100). But after inspecting the `Order` data, I realized there is not really a single key which causes the root interface to explode on which we could throw in an `any`. Because of this, Let's simply create the interface using [json-to-typescript](https://transform.tools/json-to-typescript) and paste the entire output (with its 600+ properties)... let this be the default way we handle extreme cases like this from this point forward...

 **Response length:**  same as above, leave as they are...

 **Add or update customer:** leave all as optional. It can be inferred that you must pass at least a single body param in order to make changes, but none is required, you can pass any, that is why they type all as optional, so let's do the same...

 **Keeping linter happy:** understood, go ahead with 1 and 2 👍🏼

**Comment by kbastamow** [comment]
28/07/2023 - Notion api functions

To resolve/discuss:

- [ ] **Version in the URL path is needed**. The api specifies v1 as the path in URL, like this: _https://api.notion.com/v1/search_ but our base URL doesn't include it: _baseURL: https://api.notion.com_. 
**Should we add it to base url like in our other apis, or to the individual paths?**

- [ ]  **getPages function** - this is a post method that takes both query and body params, and needs reviewing as I'm not sure how to add them both. 
[https://developers.notion.com/reference/post-database-query](https://developers.notion.com/reference/post-database-query)

- [ ] **Some functions have been omitted.** For example, listing all databases appears to be deprecated, and I haven't added a function to retrieve tables (just pages), because table option isn’t clearly outlined in the documentation.

Overall, the documentation is quite chaotic and I'm not 100% sure I'm returning the correct type of responses. The docs use examples for response data, and it appears there are a lot of changing properties depending on the type returned. There doesn't seem to have a definitive example of each. 

This api was quite tricky, so should be reviewed and tested!

**Comment by miguelrk** [comment]
**Version in the URL path is needed:** good catch, yes, we should add it to the `baseURL`. I just did this and will push to main soon.

**getPages function:** the API client currently has that limitation (you cannot pass a query and a body at the same time e.g. for this specific POST request). I would have to look into this, but in the meantime, make the `getPages` function NOT accept a query (which is only realy needed to filter results, so not even that important), and accept ONLY a body.

**Some functions have been omitted:** noted, I will have a look into testing this API later but looks good to me for now 👍🏼...

**Comment by kbastamow** [comment]
28/07/2023 - Hubspot api functions

- [ ] **URLs point to different versions** - Some of the version 3 apis are still in Beta state according to official documentation, e.g. forms:  [https://developers.hubspot.com/docs/api/marketing/forms](https://developers.hubspot.com/docs/api/marketing/forms)
I've now mapped the functions to their stable versions, so some are v3 but there's also v2 and even v1. We should keep on eye on this to update the functions when the new versions are ready.

**Comment by miguelrk** [comment]
**URLs point to different versions** - alright, looks fine. In this case, since the version mismatch is part of the path, we can use different versions for different operations, if it were part of the baseURL, I'd say we simply omit operations requiring beta endpoints. But let's keep these as they are, as these functions should be tested anyway, and tests should indicate any breaking changes in versions and prompt us to update when that happens.

**Pull request merged**
