### PR TITLE
chore: refactor cli to support local cloning

### PR DESCRIPTION
**Pull request by deer**
Working towards the first part of the next steps in https://github.com/netzo/netzo/pull/91.

Still need to add tests. Also need to investigate behavior when installed, instead of run remotely (e.g. deno run -A https://raw.githubusercontent.com/deer/netzo/56ec38dd1aae53bdeb4751f8c16d0e46a31c7ca7/lib/cli/netzo.ts init, which does pick 0.4.28, because this is a remote script).

### CODE REVIEW

**Comment by deer** [comment]
Good news is that the install command behaves as expected:
```
deno install -Arf  deno install -Arf  https://raw.githubusercontent.com/deer/netzo/56ec38dd1aae53bdeb4751f8c16d0e46a31c7ca7/lib/cli/netzo.ts
✅ Successfully installed netzo
/Users/reed/.deno/bin/netzo
```
then:
```
netzo init
? Select a template: minimal
✨ Successfully cloned netzo-netzo to minimal
```
and if i do it locally:
```
deno install -Arf netzo/lib/cli/netzo.ts
✅ Successfully installed netzo
/Users/reed/.deno/bin/netzo
```
I get:
```
netzo init
? Select a template: minimal
```
(This is a bug that I'm about to fix, but I left so that I could easily determine whether it's doing remote or not.)

**Comment by deer** [comment]
Now we get better messages when running locally:
```
deno run -A netzo/lib/cli/netzo.ts init
? Select a template: minimal
✨ Successfully cloned /Users/reed/code/netzo/netzo/templates/minimal to minimal
```

And in the unlikely event that someone installs locally:
```
netzo init
? Select a template: minimal
✨ Successfully cloned /Users/reed/code/netzo/netzo/templates/minimal to minimal
```

**Comment by deer** [comment]
@miguelrk, this is ready now. Let's see if we can keep things green. I still have the todo about another test case (programmatically modifying the template and invoking the newly added route), but I also wanted to highlight the need for a better release workflow. Your commit to release 0.4.28 broke formatting, but in general this should be an automated instead of manual process.

I"ll log some issues now.

**Review by miguelrk — APPROVED** [review]
This is great! Thanks for this, will merge...

**Pull request merged**
