### PR TITLE
chore: cleanup some linting errors

### PR DESCRIPTION
**Pull request by deer**
towards https://github.com/netzo/netzo/issues/112

When I rerun the analysis mentioned in the issue, we now get:
```
no-explicit-any: 65
```
and
```
{
  "no-explicit-any": {
    files: [
      "./lib/components/blocks/form/fields/array.tsx",
      "./lib/components/blocks/form/fields/enum.tsx",
      "./lib/components/blocks/form/fields/object.tsx",
      "./lib/components/blocks/form/fields/radio-group.tsx",
      "./lib/components/blocks/form/types.ts",
      "./lib/components/blocks/form/utils.ts",
      "./lib/hooks/use-ui.ts",
      "./lib/plugins/api/errors.ts",
      "./lib/plugins/api/utils.ts"
    ],
    count: 65
  }
}
```

I"m not sure if this will break anything, since the testing situation is non-existent 😅

### CODE REVIEW

**Comment by deer** [comment]
I should mention this also takes us from
```
Found 430 errors.
```
to
```
Found 424 errors.
```
for `deno task check:types`.

**Review by miguelrk — COMMENTED** [review]
Looking good 👌🏼 ... On a related note, I started working on the `resources` module via https://github.com/netzo/netzo/pull/116, it's no way near feature-complete but I've been cleaning up code/types as well.

**Comment by deer** [comment]
I've realized we can enable this in CI now.

**Comment by deer** [comment]
@miguelrk, I've merged main and I've partially enabled linting in CI via `deno lint --rules-exclude=no-explicit-any`. This will at least prevent any other problems from sneaking in.

**Review by miguelrk — APPROVED** [review]
Nice to have linting in CI/CD in place, we can tackle the `any`s progressively 😆 ...

**Pull request merged**
